language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - yasm
    - libxinerama-dev
    - libxcursor-dev
    - libglu1-mesa-dev
    - libboost-all-dev
    - libx264-dev
    - libxrandr-dev
    - libxi-dev
    - libglew-dev
    - vpx-tools
    - binutils
    - libjpeg-turbo8-dev

before_script:
  - sudo add-apt-repository -y ppa:keithw/glfw3
  - sudo apt-get update -qq
  - sudo apt-get install -y --allow-unauthenticated libglfw3-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 99

script:
  - ./autogen.sh
  - ./configure
  - make -j3 distcheck V=1 || (cat alfalfa-0.1/_build/src/tests/test-suite.log && exit 1)

notifications:
  slack: keithw:2nINWkhRQ60BzeTDNYXgpLkU
